### ISSUE TITLE
TypeError: Cannot read property 'roles' of undefined while using !eval

### ISSUE THREAD

**Issue by pfilippi24** [AWulkan/Mr-Roboto#1]
As in title

![image](https://cloud.githubusercontent.com/assets/4476695/22857424/07febc6e-f0a5-11e6-9b2b-4acec6cc2a9a.png)

**Comment by AWulkan** [comment]
The issue should be resolved in this update: https://github.com/AWulkan/Mr-Roboto/commit/edc6c5b5f83122f7e55b35b4990a57b8a8d273f2

I think I created some recursion by overwriting the eval function. ¯\\_(ツ)_/¯
